name: Tests

on:
  workflow_call:
    secrets:
      inherit: true

jobs:      
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set Up
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'
      
      - name: Test with pytest
        run: |
          pytest -m 'not (cost or local)'
